Repository AICoE/aicoe-ci, pull requests merged in 2020-06, with the labels that each got.

#29 use label to separate the pipelines
  trigger/git-issue-template.yaml
  trigger/git-pr-template.yaml
  trigger/git-tag-template.yaml
Labels: approved, size/S

#31 Use s2i-thoth-ubi8-py36:v0.13.0
  tasks/resource.yaml
Labels: approved, size/XS

#28 publish python module to pypi through aicoe-ci
  conditions/upload-pypi-check.yaml
  kustomization.yaml
  manifests/secrets.enc.yaml
  pipeline/tag-release-pipeline.yaml
  tasks/upload-pypi.yaml
Labels: approved, size/L

#32 removed all coala related things
  kustomization.yaml
  pipeline/pipeline.yaml
  tasks/coala-checks.yaml
  tasks/status-task.yaml
Labels: approved, size/L

#35 no more verbose about unknown commands
  tasks/init-task.yaml
Labels: approved, size/S

#34 no pipeline will no longer merge any PR
  pipeline/pipeline.yaml
  tasks/init-task.yaml
  trigger/git-pr-binding.yaml
  trigger/git-pr-template.yaml
Labels: approved, size/M
