Repository AICoE/aicoe-ci, pull requests merged in 2020-05, with the labels that each got.

#15 Display the pipelinerun associated with tasks
  pipeline/pipeline.yaml
  tasks/coala-checks.yaml
  tasks/pr-build.yaml
  tasks/pytest-checks.yaml
  trigger/git-pr-template.yaml
Labels: approved, size/M

#17 :sparkles: now we also support a Containerfile
  .gitignore
  tasks/pr-build-release.yaml
  tasks/pr-build.yaml
  tasks/tag-release-task.yaml
Labels: enhancement, size/M

#19 using updated builder image
  tasks/resource.yaml
Labels: do-not-merge/needs-rebase, size/XS

#18 WIP: Pre commit task
  tasks/pre-commit-check.yaml
Labels: approved, do-not-merge/work-in-progress, size/M
