Repository AICoE/aicoe-ci, pull requests merged in 2020-10, with the labels that each got.

#70 allow users to push the tag image to another custom tag
  docs/.aicoe-ci.yaml
  pipeline/tag-release-pipeline.yaml
  tasks/configuration-task.yaml
  tasks/tag-release-task.yaml
Labels: approved, size/M

#71 use default project name if not set in configuration
  tasks/issue-release-task.yaml
Labels: approved, size/XS

#73 Add Rebase Task
  conditions/approve-comment-check.yaml
  conditions/issue-check.yaml
  kustomization.yaml
  pipeline/issue-pipeline.yaml
  setup-instance/kustomization.yaml
  tasks/example-issue.yaml
  tasks/issue-check.yaml
  tasks/repo-upstream-sync.yaml
  trigger/git-issue-binding.yaml
Labels: approved, size/L
