Repository AICoE/aicoe-ci, pull requests merged in 2021-04, with the labels that each got.

#104 updated the pull request title based on users request
  tasks/z-stream-release-task.yaml
Labels: size/M

#107 couple the release pipeline with build analysis
  tasks/overlay-build-task.yaml
  tasks/tag-release-task.yaml
Labels: size/L

#109 fix: Use rbac api group for bindings to sync nicely in ArgoCD
  manifests/overlays/moc/binding.yaml
  manifests/overlays/ocp/binding.yaml
Labels: approved, size/S
