Repository AICoE/aicoe-ci, pull requests merged in 2021-11, with the labels that each got.

#129 Automate Onboarding to Cluster OPF via CLI
  example-taskruns/create-github-release-taskrun.yaml
  example-taskruns/github-release-taskrun.yaml
  kustomization.yaml
  pipeline/onboarding-issue-pipeline.yaml
  tasks/create-github-release.yaml
  tasks/github-release-taskrun.yaml
  tasks/github-release.yaml
  tasks/onboarding-issue-task.yaml
  tasks/resource.yaml
  trigger/eventlistener.yaml
  trigger/onboarding-issue-binding.yaml
  triggertemplate/onboarding-issue-template.yaml
Labels: approved, size/XL

#147 check the owners file in the repo as well as github association rules
  .github/ISSUE_TEMPLATE/request_sesheta.yaml
  tasks/init-task.yaml
Labels: approved, size/XS

#140 creating the github-release tekton task
  tasks/onboarding-issue-task.yaml
  trigger/eventlistener.yaml
Labels: size/XS

#152 Update approvers/reviewers plus minor improvements
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .pre-commit-config.yaml
  OWNERS
  README.md
  docs/how-to-contribute.md
Labels: approved, size/M

#149 updating tekton trigger definitions to 14.2
  manifests/overlays/moc/kustomization.yaml
  manifests/overlays/moc/listener.yaml
Labels: approved, size/L
