Repository AICoE/aicoe-ci, pull requests merged in 2022-02, with the labels that each got.

#161 :city_sunrise: Allow arch build with overlays feature
  pipeline/overlays-release-pipeline.yaml
  tasks/overlay-build-task.yaml
  tasks/overlay-deploy-task.yaml
  tasks/overlays-pipeline.yaml
Labels: approved, size/L

#163 :turtle: Enable image digest and image info set as result
  tasks/tag-release-task.yaml
Labels: size/S, approved

#164 :turtle: Enable few of orgs to sign the image with chains
  manifests/overlays/moc/serviceaccount.yaml
  tasks/issue-release-task.yaml
  tasks/overlay-build-task.yaml
  tasks/pr-build-release.yaml
Labels: size/M

#166 Remove maintainer list from .thoth.yaml
  .thoth.yaml
Labels: approved, size/XS
